# Generated by Django 6.0.2 on 2026-02-27 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True)),
                ('avatar_url', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_provider', models.BooleanField(default=False)),
                ('auth_provider', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('phone', 'Phone')], default='telegram', help_text='telegram | email | phone', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['telegram_id'], name='ix_users_telegram_id'), models.Index(fields=['email'], name='ix_users_email'), models.Index(fields=['created_at'], name='ix_users_created_at')],
            },
        ),
    ]
